import type {
  District,
  Incident,
  LifelineDefinition,
  Resource,
  ScenarioPreset,
} from './types'

export const lifelineDefinitions: LifelineDefinition[] = [
  { key: 'safety', label: 'Safety and Security', shortLabel: 'Safety', criticalThreshold: 62 },
  { key: 'foodWater', label: 'Food and Water', shortLabel: 'Water', criticalThreshold: 58 },
  { key: 'health', label: 'Health and Medical', shortLabel: 'Health', criticalThreshold: 60 },
  { key: 'energy', label: 'Energy', shortLabel: 'Energy', criticalThreshold: 55 },
  {
    key: 'communications',
    label: 'Communications',
    shortLabel: 'Comms',
    criticalThreshold: 52,
  },
  {
    key: 'transport',
    label: 'Transportation',
    shortLabel: 'Transport',
    criticalThreshold: 56,
  },
  { key: 'shelter', label: 'Shelter', shortLabel: 'Shelter', criticalThreshold: 57 },
]

const baseLifelines = {
  safety: 86,
  foodWater: 82,
  health: 79,
  energy: 84,
  communications: 88,
  transport: 80,
  shelter: 76,
}

export const districts: District[] = [
  {
    id: 'south-flats',
    name: 'South Flats',
    role: 'low-lying residential belt',
    population: 184_000,
    vulnerablePercent: 34,
    density: 9.1,
    elevationM: 4,
    drainageScore: 42,
    shelterBeds: 12_400,
    clinics: 6,
    backupPowerHours: 9,
    commsReliability: 0.62,
    coordinates: { x: 36, y: 70 },
    polygon: '22,58 42,55 50,70 44,86 24,84 16,70',
    lifelines: { ...baseLifelines, foodWater: 70, transport: 66, shelter: 63 },
    exposure: { flood: 0.92, wind: 0.48, heat: 0.72, landslide: 0.08 },
  },
  {
    id: 'harbor-ward',
    name: 'Harbor Ward',
    role: 'port, fisheries, fuel depots',
    population: 96_000,
    vulnerablePercent: 29,
    density: 6.7,
    elevationM: 2,
    drainageScore: 38,
    shelterBeds: 7_500,
    clinics: 3,
    backupPowerHours: 15,
    commsReliability: 0.68,
    coordinates: { x: 20, y: 49 },
    polygon: '7,34 27,31 36,45 31,58 14,61 5,50',
    lifelines: { ...baseLifelines, safety: 78, foodWater: 72, energy: 76, transport: 70 },
    exposure: { flood: 0.86, wind: 0.82, heat: 0.44, landslide: 0.05 },
  },
  {
    id: 'old-town',
    name: 'Old Town',
    role: 'dense heritage core',
    population: 221_000,
    vulnerablePercent: 41,
    density: 10,
    elevationM: 12,
    drainageScore: 51,
    shelterBeds: 9_100,
    clinics: 8,
    backupPowerHours: 6,
    commsReliability: 0.73,
    coordinates: { x: 43, y: 43 },
    polygon: '31,28 49,24 62,36 58,54 42,55 32,45',
    lifelines: { ...baseLifelines, health: 72, energy: 71, transport: 62, shelter: 58 },
    exposure: { flood: 0.58, wind: 0.48, heat: 0.87, landslide: 0.18 },
  },
  {
    id: 'central-hospital',
    name: 'Central Hospital Grid',
    role: 'tertiary hospitals and blood banks',
    population: 132_000,
    vulnerablePercent: 46,
    density: 7.6,
    elevationM: 17,
    drainageScore: 68,
    shelterBeds: 5_800,
    clinics: 16,
    backupPowerHours: 26,
    commsReliability: 0.81,
    coordinates: { x: 60, y: 55 },
    polygon: '57,52 74,49 84,61 77,76 60,77 50,68',
    lifelines: { ...baseLifelines, health: 87, shelter: 67, transport: 69 },
    exposure: { flood: 0.45, wind: 0.42, heat: 0.77, landslide: 0.12 },
  },
  {
    id: 'north-market',
    name: 'North Market',
    role: 'wholesale food and logistics',
    population: 118_000,
    vulnerablePercent: 22,
    density: 6.2,
    elevationM: 19,
    drainageScore: 61,
    shelterBeds: 8_700,
    clinics: 5,
    backupPowerHours: 14,
    commsReliability: 0.78,
    coordinates: { x: 56, y: 24 },
    polygon: '48,8 70,10 79,27 63,37 49,24',
    lifelines: { ...baseLifelines, foodWater: 88, transport: 82 },
    exposure: { flood: 0.37, wind: 0.5, heat: 0.64, landslide: 0.15 },
  },
  {
    id: 'university-ridge',
    name: 'University Ridge',
    role: 'campus, shelters, radio mast',
    population: 74_000,
    vulnerablePercent: 18,
    density: 4.1,
    elevationM: 48,
    drainageScore: 84,
    shelterBeds: 18_600,
    clinics: 4,
    backupPowerHours: 21,
    commsReliability: 0.9,
    coordinates: { x: 79, y: 38 },
    polygon: '72,18 91,25 96,43 84,61 74,49 63,37',
    lifelines: { ...baseLifelines, shelter: 91, communications: 93, transport: 78 },
    exposure: { flood: 0.22, wind: 0.72, heat: 0.51, landslide: 0.42 },
  },
  {
    id: 'industrial-belt',
    name: 'Industrial Belt',
    role: 'manufacturing and hazmat corridor',
    population: 103_000,
    vulnerablePercent: 24,
    density: 5.7,
    elevationM: 8,
    drainageScore: 47,
    shelterBeds: 6_800,
    clinics: 2,
    backupPowerHours: 18,
    commsReliability: 0.66,
    coordinates: { x: 23, y: 21 },
    polygon: '8,10 30,5 48,8 49,24 31,28 27,31 7,34',
    lifelines: { ...baseLifelines, safety: 73, health: 68, energy: 79 },
    exposure: { flood: 0.64, wind: 0.69, heat: 0.66, landslide: 0.1 },
  },
  {
    id: 'east-terminal',
    name: 'East Terminal',
    role: 'rail, bus, and relief staging',
    population: 88_000,
    vulnerablePercent: 21,
    density: 5.4,
    elevationM: 23,
    drainageScore: 64,
    shelterBeds: 10_300,
    clinics: 3,
    backupPowerHours: 17,
    commsReliability: 0.76,
    coordinates: { x: 83, y: 79 },
    polygon: '77,76 91,69 99,82 92,96 72,94 60,77',
    lifelines: { ...baseLifelines, transport: 87, shelter: 79 },
    exposure: { flood: 0.48, wind: 0.58, heat: 0.62, landslide: 0.22 },
  },
  {
    id: 'greenfield',
    name: 'Greenfield',
    role: 'peri-urban farms and reservoirs',
    population: 67_000,
    vulnerablePercent: 26,
    density: 3.3,
    elevationM: 32,
    drainageScore: 76,
    shelterBeds: 5_600,
    clinics: 2,
    backupPowerHours: 12,
    commsReliability: 0.7,
    coordinates: { x: 63, y: 87 },
    polygon: '44,86 60,77 72,94 54,99 33,95 24,84',
    lifelines: { ...baseLifelines, foodWater: 85, communications: 75, health: 70 },
    exposure: { flood: 0.52, wind: 0.43, heat: 0.73, landslide: 0.3 },
  },
]

export const incidents: Incident[] = [
  {
    id: 'inc-001',
    districtId: 'south-flats',
    title: 'Canal backflow near Pump Station 4',
    category: 'flood',
    severity: 5,
    confidence: 0.91,
    reports: 46,
    minutesAgo: 14,
    channel: 'sensor',
    summary: 'Water level sensors and field crews confirm rapid street flooding.',
  },
  {
    id: 'inc-002',
    districtId: 'old-town',
    title: 'Heat stress cluster around Bazaar Road',
    category: 'health',
    severity: 4,
    confidence: 0.82,
    reports: 17,
    minutesAgo: 28,
    channel: 'hospital',
    summary: 'Emergency rooms report rising dehydration and respiratory distress.',
  },
  {
    id: 'inc-003',
    districtId: 'harbor-ward',
    title: 'Fuel depot access road submerged',
    category: 'transport',
    severity: 4,
    confidence: 0.78,
    reports: 22,
    minutesAgo: 36,
    channel: 'field-team',
    summary: 'High-clearance vehicles required to keep depot access open.',
  },
  {
    id: 'inc-004',
    districtId: 'central-hospital',
    title: 'Ambulance queue exceeds surge protocol',
    category: 'health',
    severity: 3,
    confidence: 0.75,
    reports: 9,
    minutesAgo: 42,
    channel: 'hospital',
    summary: 'Transfer delays are beginning to affect urgent care capacity.',
  },
  {
    id: 'inc-005',
    districtId: 'industrial-belt',
    title: 'Substation trip at Line 8',
    category: 'energy',
    severity: 3,
    confidence: 0.74,
    reports: 12,
    minutesAgo: 51,
    channel: 'utility',
    summary: 'Partial outage may reduce pumping and cold-chain capacity.',
  },
  {
    id: 'inc-006',
    districtId: 'university-ridge',
    title: 'Radio mast battery warning',
    category: 'communications',
    severity: 2,
    confidence: 0.7,
    reports: 5,
    minutesAgo: 58,
    channel: 'sensor',
    summary: 'Backup mast can support priority traffic if fuel delivery arrives.',
  },
]

export const resources: Resource[] = [
  {
    id: 'rescue-01',
    type: 'rescueTeam',
    label: 'Swift-water rescue teams',
    availableUnits: 9,
    unitCapacity: 240,
    staging: { x: 73, y: 71 },
    readinessMinutes: 18,
  },
  {
    id: 'medical-01',
    type: 'medicalTeam',
    label: 'Mobile medical teams',
    availableUnits: 11,
    unitCapacity: 320,
    staging: { x: 58, y: 54 },
    readinessMinutes: 12,
  },
  {
    id: 'water-01',
    type: 'waterUnit',
    label: 'Water purification units',
    availableUnits: 7,
    unitCapacity: 1_900,
    staging: { x: 56, y: 24 },
    readinessMinutes: 25,
  },
  {
    id: 'power-01',
    type: 'powerCrew',
    label: 'Microgrid repair crews',
    availableUnits: 6,
    unitCapacity: 1_200,
    staging: { x: 23, y: 21 },
    readinessMinutes: 20,
  },
  {
    id: 'comms-01',
    type: 'commsKit',
    label: 'Satellite comms kits',
    availableUnits: 8,
    unitCapacity: 8_000,
    staging: { x: 79, y: 38 },
    readinessMinutes: 10,
  },
  {
    id: 'bus-01',
    type: 'busFleet',
    label: 'Evacuation bus fleets',
    availableUnits: 10,
    unitCapacity: 700,
    staging: { x: 83, y: 79 },
    readinessMinutes: 22,
  },
  {
    id: 'shelter-01',
    type: 'shelterTeam',
    label: 'Shelter activation teams',
    availableUnits: 12,
    unitCapacity: 950,
    staging: { x: 79, y: 38 },
    readinessMinutes: 16,
  },
]

export const scenarioPresets: ScenarioPreset[] = [
  {
    id: 'monsoon-surge',
    name: 'Monsoon Surge',
    summary: 'Urban flood pressure with hospital and transport strain.',
    controls: {
      rainfallMm: 178,
      riverLevelM: 6.8,
      windKph: 66,
      heatIndexC: 36,
      commsOutagePercent: 18,
      hospitalLoadPercent: 82,
      trafficBlockagePercent: 54,
      forecastHours: 8,
    },
  },
  {
    id: 'cyclone-landfall',
    name: 'Cyclone Landfall',
    summary: 'Wind, storm surge, grid instability, and port disruption.',
    controls: {
      rainfallMm: 132,
      riverLevelM: 5.7,
      windKph: 156,
      heatIndexC: 33,
      commsOutagePercent: 41,
      hospitalLoadPercent: 76,
      trafficBlockagePercent: 47,
      forecastHours: 10,
    },
  },
  {
    id: 'heat-health',
    name: 'Heat Health',
    summary: 'Extreme heat with medical surge and power stress.',
    controls: {
      rainfallMm: 12,
      riverLevelM: 2.6,
      windKph: 18,
      heatIndexC: 47,
      commsOutagePercent: 8,
      hospitalLoadPercent: 88,
      trafficBlockagePercent: 24,
      forecastHours: 12,
    },
  },
  {
    id: 'blackout-cascade',
    name: 'Blackout Cascade',
    summary: 'Energy and communications failure during heavy rain.',
    controls: {
      rainfallMm: 86,
      riverLevelM: 4.4,
      windKph: 92,
      heatIndexC: 39,
      commsOutagePercent: 62,
      hospitalLoadPercent: 72,
      trafficBlockagePercent: 38,
      forecastHours: 6,
    },
  },
]

export const defaultScenario = scenarioPresets[0]
